[[history]]

== 历史 History

历史是捕获流程执行过程中发生的事情，并将其永久存储的组件。与运行时数据相反，历史数据在流程实例完成以后，仍会保持在数据库中。

有5个历史实体：

* ++HistoricProcessInstance++保存当前与已结束流程实例的信息。
* ++HistoricVariableInstance++保存流程变量或任务变量的最新值。
* ++HistoricActivityInstance++保存活动（流程中的节点）的单一执行信息。
* ++HistoricTaskInstance++保存当前与过去（完成并删除的）任务实例的信息。
* ++HistoricDetail++保存与历史流程实例，活动实例或任务实例有关的多种信息。

因为数据库为过去与当前进行中的实例都保存历史实体，因此你可能希望查询这些表，以减少访问运行时流程实例数据，并提高运行时执行性能。

之后，这些信息将在Activiti Explorer中暴露。并且，也将用于生成报告。


[[historyQuery]]


=== 查询历史 Querying history

可以使用API查询全部5种历史实体，HistoryService暴露的++createHistoricProcessInstanceQuery()++、++createHistoricVariableInstanceQuery()++、++createHistoricActivityInstanceQuery()++、++createHistoricDetailQuery()++与++createHistoricTaskInstanceQuery()++方法。

下面是一些例子，展示了历史查询API的一些用法。关于各用法的全部描述可以在link:$$http://activiti.org/javadocs/index.html$$[javadoc]中找到，在++org.activiti.engine.history++包中。

[[historyQueryProcessInstance]]


==== 历史流程实例查询 HistoricProcessInstanceQuery

取得所有流程中，前10个花费最多时间完成（最长持续时间）的，定义为'XXX'，已完成的++HistoricProcessInstances++。

[source,java,linenums]
----
historyService.createHistoricProcessInstanceQuery()
  .finished()
  .processDefinitionId("XXX")
  .orderByProcessInstanceDuration().desc()
  .listPage(0, 10);
----


[[historyQueryVariableInstance]]


==== 历史变量实例查询 HistoricVariableInstanceQuery

在已完成的，id为'XXX'的流程实例中，取得所有++HistoricVariableInstances++，以变量名排序。

[source,java,linenums]
----
historyService.createHistoricVariableInstanceQuery()
  .processInstanceId("XXX")
  .orderByVariableName.desc()
  .list();
----

[[historyQueryActivityInstance]]


==== 历史活动实例查询 HistoricActivityInstanceQuery

取得最新的，服务任务类型的，已完成的，流程定义的id为XXX的，++HistoricActivityInstance++。

[source,java,linenums]
----
historyService.createHistoricActivityInstanceQuery()
  .activityType("serviceTask")
  .processDefinitionId("XXX")
  .finished()
  .orderByHistoricActivityInstanceEndTime().desc()
  .listPage(0, 1);
----

[[historyQueryDetail]]


==== 历史详情查询 HistoricDetailQuery

下一个例子，取得id为123的流程中，所有变量的更新记录。这个查询只会返回++HistoricVariableUpdate++。请注意有可能某个变量名有多个++HistoricVariableUpdate++实体，代表流程中的每一次变量更新。可以使用++orderByTime++（变量更新的时间）或++orderByVariableRevision++（运行时变量更新时的版本号），按其发生顺序排序。

[source,java,linenums]
----
historyService.createHistoricDetailQuery()
  .variableUpdates()
  .processInstanceId("123")
  .orderByVariableName().asc()
  .list()
----

这个例子，取得流程id为"123"的，任何任务中或启动时提交的，所有<<formProperties,表单参数>>。这个查询只返回++HistoricFormProperties++。

[source,java,linenums]
----
historyService.createHistoricDetailQuery()
  .formProperties()
  .processInstanceId("123")
  .orderByVariableName().asc()
  .list()
----

最后一个例子，取得id为"123"的任务进行的所有变量更新操作。将返回该任务设置的所有变量（任务局部变量）的++HistoricVariableUpdates++，而**不会**返回流程实例中设置的。

[source,java,linenums]
----
historyService.createHistoricDetailQuery()
  .variableUpdates()
  .taskId("123")
  .orderByVariableName().asc()
  .list()
----

可以在++TaskListener++中使用++TaskService++或++DelegateTask++设置任务局部变量：

[source,java,linenums]
----
taskService.setVariableLocal("123", "myVariable", "Variable value");
----

[source,java,linenums]
----
public void notify(DelegateTask delegateTask) {
  delegateTask.setVariableLocal("myVariable", "Variable value");
}
----

[[historyQueryTaskInstance]]


==== 历史任务示例查询  HistoricTaskInstanceQuery

取得所有任务中，前10个花费最多时间完成（最长持续时间）的，已完成的++HistoricTaskInstance++。

[source,java,linenums]
----
historyService.createHistoricTaskInstanceQuery()
  .finished()
  .orderByHistoricTaskInstanceDuration().desc()
  .listPage(0, 10);
----

取得删除原因包含"invalid"，最后一次指派给'kermit'用户的++HistoricTaskInstance++。

[source,java,linenums]
----
historyService.createHistoricTaskInstanceQuery()
  .finished()
  .taskDeleteReasonLike("%invalid%")
  .taskAssignee("kermit")
  .listPage(0, 10);
----


[[historyConfig]]

=== 历史配置 History configuration

可以使用org.activiti.engine.impl.history.HistoryLevel枚举（或在5.11版本前，++ProcessEngineConfiguration++中定义的__HISTORY__常量），以编程方式配置历史级别：

[source,java,linenums]
----
ProcessEngine processEngine = ProcessEngineConfiguration
  .createProcessEngineConfigurationFromResourceDefault()
  .setHistory(HistoryLevel.AUDIT.getKey())
  .buildProcessEngine();
----

也可以在activiti.cfg.xml或Spring上下文中配置级别：

[source,xml,linenums]
----
<bean id="processEngineConfiguration" class="org.activiti.engine.impl.cfg.StandaloneInMemProcessEngineConfiguration">
  <property name="history" value="audit" />
  ...
</bean>
----

可以配置下列历史级别：

* ++none（无）++：跳过所有历史存档。对于运行时流程执行来说，是性能最高的配置，但是不会保存任何历史信息。
* ++activity（活动）++：存档所有流程实例与活动实例。在流程实例结束时，顶级流程实例变量的最新值，将被复制为历史流程实例。不会存档细节。
* ++audit（审计）++：默认级别。将存档所有流程实例，活动实例，并保持变量值以及所有提交的表单参数持续同步，以保证表单的所有用户操作都可追踪、可审计。
* ++full（完全）++：历史存档的最高级别，因此也最慢。这个级别存储所有++audit++级别存储的信息，加上所有其他可用细节，主要是流程变量的更新。

**在Activiti 5.11版本以前，历史级别保存在数据库中（+$$ACT_GE_PROPERTY$$+ 表，参数名为++historyLevel++）。从5.11开始，这个值不再使用，并从数据库中忽略/删除。现在历史可以在2个引擎的启动间切换，而不会由于前一个引擎启动修改了级别，而抛出异常。**

[[historyFormAuditPurposes]]


=== 审计目的历史 History for audit purposes

如果至少<<historyConfig,配置>>为++audit++级别，则通过++FormService.submitStartFormData(String processDefinitionId, Map<String, String> properties)++与++FormService.submitTaskFormData(String taskId, Map<String, String> properties)++方法提交的所有参数都将被记录。

表单参数可以通过查询API，像这样读取：

[source,java,linenums]
----
historyService
      .createHistoricDetailQuery()
      .formProperties()
      ...
      .list();
----

在这个情况下，只会返回++HistoricFormProperty++类型的历史详情。

如果在调用提交方法前，使用++IdentityService.setAuthenticatedUserId(String)++设置了认证用户，则该提交了表单的认证用户可以在历史中访问。对于启动表单使用++HistoricProcessInstance.getStartUserId()++，对于任务表单使用++HistoricActivityInstance.getAssignee()++。
