
== 高级 Advanced

下面的章节介绍了Activiti的高级用例，超出了一般的BPMN 2.0流程执行的范畴。因此，要理解这里的材料需要对Activiti足够熟练与精通。

[[advanced_parseHandlers]]

=== 异步与作业执行器 Async and job executor

从5.17.0版本开始，Activiti在已有的作业执行器之外，还提供了异步执行器。在Activiti引擎中，两个执行器都处理定时器与异步作业，因此只能启用一个执行器。这个章节将介绍异步执行器与作业执行器的区别，以及为什么我们推荐使用异步执行器。请注意默认情况下Activiti使用已有的作业执行器，因为我们不希望没有进行明确的配置就启用异步执行器。

==== 异步执行器的设计 Async executor design

异步执行器包含了一个用于执行定时器与异步作业的线程池。当启用时，引擎将会使用已经持久化的异步作业实体调用异步执行器，然后线程池将异步地执行该作业。这是与老的作业执行器的主要区别，因为在异步作业已被持久化的情况下，作业执行器将会轮询数据库获取新作业。如果找到了一个作业，将锁定并执行它，这意味着大量额外的数据库通信。异步执行器会直接执行异步作业，而不会先轮询数据库。如果异步作业是一个排他作业，异步执行器将首先锁定流程实例的执行，如果成功则将执行作业，并之后解锁流程实例执行。如果锁定流程实例失败，则会重试。

定时器作业的逻辑与异步作业不同。对于定时器作业，异步与作业执行器的实现相近。异步执行器将轮询数据库中到期的定时器作业。然后会锁定并执行作业。

==== 作业执行器的设计 Job executor design

作业执行器也包含了一个用于执行定时器与异步作业的线程池。当启用时，作业执行器会轮询数据库，获取异步作业与定时器作业的到期时间。如果找到了一个作业，执行器将锁定并执行该作业，这意味着大量额外的数据库通信。相对应的，异步执行器会直接执行异步作业，而不会首先轮询数据库。

==== 异步执行器的优点 Advantages of the Async executor

* 更少的数据库查询，因为异步作业不通过轮询数据库就执行
* 对于非排他作业，不会再遇到OptimisticLockingExceptions（乐观锁异常）
* 排他作业现在锁定在流程实例级别，而不是在作业执行器中那样，使用笨重的逻辑查询排他作业。

==== 配置异步执行器 Async executor configuration

可以为异步执行器定义线程池大小与其他配置项。我们建议查看异步执行器的默认设置，核实其是否符合你的流程实例的要求。

要覆盖异步执行器的默认设置，需要在流程引擎配置中注入一个新的bean，像是：

[source,xml,linenums]
----
<property name="asyncExecutor" ref="asyncExecutor" />
----

可以覆盖默认的异步执行器，以覆盖默认设置，当然也可以从DefaultAsyncJobExecutor类扩展。下面列出的配置中，DefaultAsyncJobExecutor的参数使用了新的值：

[source,xml,linenums]
----
<bean id="asyncExecutor" class="org.activiti.engine.impl.asyncexecutor.DefaultAsyncJobExecutor">
    <property name="corePoolSize" value="10" />
    <property name="maxPoolSize" value="50" />
    <property name="keepAliveTime" value="3000" />
    <property name="queueSize" value="200" />
    <property name="maxTimerJobsPerAcquisition" value="2" />
    <property name="maxAsyncJobsDuePerAcquisition" value="2" />
    <property name="defaultAsyncJobAcquireWaitTimeInMillis" value="1000" />
    <property name="defaultTimerJobAcquireWaitTimeInMillis" value="1000" />
    <property name="timerLockTimeInMillis" value="60000" />
    <property name="asyncJobLockTimeInMillis" value="60000" />
</bean>
----

.异步执行器配置选项
[options="header"]
|===============
|名字|默认值|描述
|corePoolSize|2|线程池中为执行作业保留的最小线程数量。
|maxPoolSize|10|线程池中为执行作业保留的最大线程数量。
|keepAliveTime|5000|在销毁执行作业所用的线程前，需要保持活动的时间（以毫秒计）。默认设置为5000。设置为非默认的0值会消耗资源，但在有大量执行作业的时候，可以避免总是创建新线程。

|queueSize|100|放置待执行作业的队列的大小。
|maxTimerJobsPerAcquisition|1|在一次查询中获取的将到期定时器作业的数量。
|maxAsyncJobsDuePerAcquisition|1|在一次数据库查询中获取的异步作业的数量。
|defaultAsyncJobAcquireWaitTimeInMillis|10000|在两次执行异步作业查询之间等待的时间，以毫秒计。
|defaultTimerJobAcquireWaitTimeInMillis|10000|在两次执行将到期定时器作业查询之间等待的时间，以毫秒计。
|timerLockTimeInMillis|300000|在重试之前，定时器作业进行锁定操作的时间，以毫秒计。在该时间之后，Activiti引擎会视为定时器作业已经失败，并将重试锁定。

|asyncJobLockTimeInMillis|300000|在重试之前，异步作业进行锁定操作的时间，以毫秒计。在该时间之后，Activiti引擎会视为异步作业已经失败，并将重试锁定。

|===============

=== 深入流程解析 Hooking into process parsing

一个BPMN 2.0 XML需要解析为Activiti的内部模型，才能在Activiti引擎中执行。解析发生在部署流程时；或没有在内存中找到流程的时候，这时将会从数据库获取XML。

对于每一个流程，++BpmnParser++类都会创建一个新的++BpmnParser++实例。这个实例是所有在解析时要做的事情的容器。解析本身很简单：对于每一个BPMN 2.0元素，引擎中都有一个对应的++org.activiti.engine.parse.BpmnParseHandler++的实例。因此，解析器会将一个BPMN 2.0元素类映射至一个++BpmnParseHandler++实例。默认情况下，Activiti使用++BpmnParseHandler++实例处理所有支持的元素，并用其为流程的步骤附加执行监听器，以创建历史。

可以在Activiti引擎中添加++org.activiti.engine.parse.BpmnParseHandler++的自定义实例。常见使用场景是，例如为特定步骤添加执行监听器，用于向某个事件处理队列触发事件。Activiti内部使用这种方式处理历史。要添加这种自定义处理器，需要调整Activiti配置：

[source,xml,linenums]
----
<property name="preBpmnParseHandlers">
  <list>
    <bean class="org.activiti.parsing.MyFirstBpmnParseHandler" />
  </list>
</property>

<property name="postBpmnParseHandlers">
  <list>
    <bean class="org.activiti.parsing.MySecondBpmnParseHandler" />
    <bean class="org.activiti.parsing.MyThirdBpmnParseHandler" />
  </list>
</property>
----

在++preBpmnParseHandlers++参数中配置的++BpmnParseHandler++实例的列表将添加在任何默认处理器之前。类似的，++postBpmnParseHandlers++中的将添加在默认处理器之后。在顺序会影响自定义解析处理器中包含的逻辑时很重要。

++org.activiti.engine.parse.BpmnParseHandler++是一个简单的接口：

[source,java,linenums]
----
public interface BpmnParseHandler {

  Collection<Class>? extends BaseElement>> getHandledTypes();

  void parse(BpmnParse bpmnParse, BaseElement element);

}
----

++getHandledTypes()++方法返回该解析器处理的所有类型的集合。通过集合的泛型决定了可用的类型是++BaseElement++的子类。也可以扩展++AbstractBpmnParseHandler++类，并覆盖++getHandledType()++方法，它只返回一个类而不是一个集合。这个类也包含了一些默认解析处理器共享的辅助方法。当解析器遇到任何该方法的返回类型时，将调用++BpmnParseHandler++实例。在下面的例子里，当遇到BPMN 2.0 XML中包含的流程时，将会执行++executeParse++方法（这是一个类型转换方法，取代了++BpmnParseHandler++接口中的普通++parse++方法）中的逻辑。

[source,java,linenums]
----
public class TestBPMNParseHandler extends AbstractBpmnParseHandler<Process> {

  protected Class<? extends BaseElement> getHandledType() {
    return Process.class;
  }

  protected void executeParse(BpmnParse bpmnParse, Process element) {
     ..
  }

}
----

**重要提示：**在撰写自定义解析处理器时，不要使用任何用于解析BPMN 2.0结构的内部类。这将导致很难查找bug。实现一个自定义处理器安全的做法是实现__BpmnParseHandler__接口，或扩展内部抽象类__org.activiti.engine.impl.bpmn.parser.handler.AbstractBpmnParseHandler__。

可以（但不常见）替换默认用于将BPMN 2.0元素解析为Activiti内部模型的++BpmnParseHandler++实例。可以通过下面的代码片段实现：

[source,xml,linenums]
----
<property name="customDefaultBpmnParseHandlers">
  <list>
    ...
  </list>
</property>
----

简单的例子是用于将所有服务任务都强制异步执行：

[source,java,linenums]
----
public class CustomUserTaskBpmnParseHandler extends ServiceTaskParseHandler {

  protected void executeParse(BpmnParse bpmnParse, ServiceTask serviceTask) {

    // 进行常规操作 Do the regular stuff
    super.executeParse(bpmnParse, serviceTask);

    // 保证异步 Make always async
    ActivityImpl activity = findActivity(bpmnParse, serviceTask.getId());
    activity.setAsync(true);
  }

}
----


[[advanced.uuid.generator]]


=== 高并发下使用的UUID id生成器 UUID id generator for high concurrency

在某些（非常）高并发负载的情况下，默认的id生成器可能会由于不能足够快地获取新的id块而产生异常。每一个流程引擎都有一个id生成器。默认的id生成器在数据库中保留一个块的id，这样其他引擎就不能使用同一个块中的id。在引擎操作时，当默认的id生成器发现id块已经用完，就会启动一个新的事务，来获取一个新的块。在（非常）有限的使用场景下，当负载非常高时可能导致问题。对于大多数用例来说，默认的id生成器已经足够使用了。默认的++org.activiti.engine.impl.db.DbIdGenerator++也有一个++idBlockSize++参数，用于配置保留的id块的大小，可以调整获取id的行为。

默认的id生成器的替代品是++org.activiti.engine.impl.persistence.StrongUuidGenerator++，它会在本地生成一个唯一的link:$$http://en.wikipedia.org/wiki/Universally_unique_identifier$$[UUID]，并将其用作所有实体的标识符。因为UUID不需要访问数据库就能生成，因此在非常高并发的使用场景下更合适。请注意取决于机器，性能可能与默认的id生成器不同（更好更坏都有可能）。

可以在activiti配置中，像下面这样配置UUID生成器：

[source,xml,linenums]
----
<property name="idGenerator">
    <bean class="org.activiti.engine.impl.persistence.StrongUuidGenerator" />
</property>
----

使用UUID id生成器需要添加下列额外依赖：

[source,xml,linenums]
----
 <dependency>
    <groupId>com.fasterxml.uuid</groupId>
    <artifactId>java-uuid-generator</artifactId>
    <version>3.1.3</version>
</dependency>
----


[[advanced.tenancy]]


=== 多租户 Multitenancy

总的来说，多租户是一个软件为多个不同组织提供服务的概念。其核心是数据是隔离的，一个组织不能看到其他组织的数据。在这个语境中，一个这样的组织（或部门、团队……）被称为一个__租户（tenant）__。

请注意它与多实例安装方式有本质区别，其中多实例安装是指每一个组织都分别运行一个Activiti流程引擎实例（并使用不同的数据库账户）。尽管Activiti比较轻量级，运行一个流程引擎实例不会花费太多资源，但多实例安装仍然增加了复杂性与维护量。但是，在某些使用场景中，多实例安装可能是正确的解决方案。

Activiti中的多租户主要围绕着隔离数据实现。要注意__Activiti并不强制多租户规则__。这意味着当查询与使用数据时，并不会验证进行操作的用户是否属于正确的租户。这应该在调用Activiti引擎的层次实现。Activiti确保可以存储租户信息，并在获取流程数据时使用。

在Activiti流程引擎中部署流程定义时，可以传递一个__租户标识符（tenant identifier）__。这是一个字符串（例如一个UUID，部门id，等等……），限制为256个字符长，唯一标识租户：

[source,java,linenums]
----
repositoryService.createDeployment()
            .addClassPathResource(...)
            .tenantId("myTenantId")
            .deploy();
----

在部署时传递一个租户id带有下列含义：

* 部署中包含的所有流程定义都将从该部署集成租户标识符。
* 从这些流程定义启动的所有流程实例都将从流程定义继承租户标识符。
* 在执行流程实例时，运行时创建的所有任务都将从流程实例继承租户标识符。独立任务也可以有租户标识符。
* 执行流程实例时创建的所有执行都将从流程实例继承租户标识符。
* 触发一个信号抛出事件（在流程内或通过API）时可以提供一个租户标识符。这个信号将只在该租户的上下文中执行：也就是说，如果有多个使用相同名字的信号捕获事件，只会调用带有正确租户标识符的事件。
* 所有作业（定时器与异步延续）要么从流程定义（例如定时器启动事件），要么从流程实例（运行时创建的作业，例如异步延续）继承租户标识符。这可以用于在自定义作业执行器中为部分租户设置优先级。
* 所有历史实体（历史流程实例、任务与活动）都从其对应的运行时对象继承租户标识符。
* 另外，模型也可以有租户标识符（模型在例如Activiti Modeler存储BPMN 2.0模型的时候使用）。

为了实际使用流程数据上的租户标识符，所有查询API都可以通过租户过滤。例如（也可以使用其他实体的对应查询实现替换）：

[source,java,linenums]
----
runtimeService.createProcessInstanceQuery()
    .processInstanceTenantId("myTenantId")
    .processDefinitionKey("myProcessDefinitionKey")
    .variableValueEquals("myVar", "someValue")
    .list()
----

查询API也可以使用__like__语义通过租户标识符过滤，也可以过滤掉没有租户标识符的实体。

**重要的实现细节：**由于数据库的原因（更确切地说，唯一约束的null处理），__默认的__代表__没有租户__的租户标识符为**空字符串**。（流程定义key，流程定义版本，租户标识符）的组合需要是唯一的（并且通过数据库约束检查）。也请注意租户标识符不能设置为null，不然会影响查询，因为某些数据库（Oracle）将空字符串当做null值（这就是为什么__.withoutTenantId__查询不检查空字符串还是null）。这意味着同一个流程定义（有相同的流程定义key）可以为多个租户部署，每一个租户都有他们自己的版本。未使用租户时不会影响使用。

**请注意上面所说都不与在集群中运行多个Activiti实例冲突。**

[试验性] 可以调用__repositoryService__的__changeDeploymentTenantId(String deploymentId, String newTenantId)__方法修改租户标识符。这将修改每一处之前继承的租户标识符。在从非多租户环境迁移至多租户配置时很有用。查看该方法的Javadoc了解更多细节信息。

[[advanced.custom.sql.queries]]


=== 执行自定义SQL Execute custom SQL

Activiti API可以通过高级API与数据库交互。例如，要获取数据，查询API与原生（Native）查询API各有用武之地。然而，在某些用例下，可能不够灵活。下面的章节描述了如何在Activiti数据存储中执行完全自定义的SQL语句（select、insert、update与delete都可以），且完全在配置的流程引擎范围内（例如因此可以使用事务设置）。

要定义自定义SQL语句，activiti引擎使用其底层框架MyBatis的功能。可以在link:$$http://mybatis.github.io/mybatis-3/java-api.html$$[MyBatis用户手册中]阅读更多信息。

==== 基于注解的映射语句 Annotation based Mapped Statements

当使用基于注解的映射语句时，首先要做的是创建一个ByBatis映射类。例如，假设在某个用例中，不需要所有的任务数据，而只需要其中很少一部分。可以通过映射类完成，像是这样：

[source,java,linenums]
----
public interface MyTestMapper {

    @Select("SELECT ID_ as id, NAME_ as name, CREATE_TIME_ as createTime FROM ACT_RU_TASK")
    List<Map<String, Object>> selectTasks();

}
----

该映射类必须像下面这样提供给流程引擎配置：

[source,xml,linenums]
----
...
<property name="customMybatisMappers">
  <set>
    <value>org.activiti.standalone.cfg.MyTestMapper</value>
  </set>
</property>
...
----

请注意这是一个接口。底层的MyBatis框架会构造一个它的实例，并在运行时使用。也请注意方法的返回值没有类型，而只是一个map的list（代表了带有列数据的行的列表）。如果需要，可以通过MyBatis映射类设置类型。

要执行上面的查询，必须使用__managementService.executeCustomSql__方法。这个方法使用一个__CustomSqlExecution__实例。这是一个包装器，将引擎需要处理的内部数据隐藏起来。

不幸的是，Java泛型让它没有本应该的那么可读。下面的两个泛型类是映射类与其返回类型类。然而，实际的逻辑就是简单的调用映射方法，并返回其结果（若有）。

[source,java,linenums]
----
CustomSqlExecution<MyTestMapper, List<Map<String, Object>>> customSqlExecution =
          new AbstractCustomSqlExecution<MyTestMapper, List<Map<String, Object>>>(MyTestMapper.class) {

  public List<Map<String, Object>> execute(MyTestMapper customMapper) {
    return customMapper.selectTasks();
  }

};

List<Map<String, Object>> results = managementService.executeCustomSql(customSqlExecution);
----

在这个例子里，上面列出的映射实体只包含__id, name与创建时间__，而不是完整的任务对象。

上面的方法可以使用任何SQL。另一个更复杂的例子：

[source,java,linenums]
----
    @Select({
        "SELECT task.ID_ as taskId, variable.LONG_ as variableValue FROM ACT_RU_VARIABLE variable",
        "inner join ACT_RU_TASK task on variable.TASK_ID_ = task.ID_",
        "where variable.NAME_ = #{variableName}"
    })
    List<Map<String, Object>> selectTaskWithSpecificVariable(String variableName);
----

使用这个方法，会将任务表与变量表联合。只选择变量有特定名字的记录，并返回任务id与对应的数字值。

对于使用基于注解的映射语句的实际例子，请查看单元测试__org.activiti.standalone.cfg.CustomMybatisMapperTest__与src/test/java/org/activiti/standalone/cfg/、src/test/resources/org/activiti/standalone/cfg/目录中的其它类与资源。


==== 基于XML的映射语句 XML based Mapped Statements

当使用基于XML的映射语句时，语句在XML文件中定义。对于不需要整个任务数据，而只需要其中很少一部分的用例来说，XML文件像是下面这样：

[source,xml,linenums]
----
<mapper namespace="org.activiti.standalone.cfg.TaskMapper">

  <resultMap id="customTaskResultMap" type="org.activiti.standalone.cfg.CustomTask">
    <id property="id" column="ID_" jdbcType="VARCHAR"/>
    <result property="name" column="NAME_" jdbcType="VARCHAR"/>
    <result property="createTime" column="CREATE_TIME_" jdbcType="TIMESTAMP" />
  </resultMap>

  <select id="selectCustomTaskList" resultMap="customTaskResultMap">
    select RES.ID_, RES.NAME_, RES.CREATE_TIME_ from ACT_RU_TASK RES
  </select>

</mapper>
----

结果映射为__org.activiti.standalone.cfg.CustomTask__类的实例，像是下面这样：

[source,java,linenums]
----
public class CustomTask {

  protected String id;
  protected String name;
  protected Date createTime;

  public String getId() {
    return id;
  }
  public String getName() {
    return name;
  }
  public Date getCreateTime() {
    return createTime;
  }
}
----

必须像下面这样为流程引擎配置提供映射XML文件：

[source,xml,linenums]
----
...
<property name="customMybatisXMLMappers">
  <set>
    <value>org/activiti/standalone/cfg/custom-mappers/CustomTaskMapper.xml</value>
  </set>
</property>
...
----

语句可以如下执行：

[source,java,linenums]
----
List<CustomTask> tasks = managementService.executeCommand(new Command<List<CustomTask>>() {

      @SuppressWarnings("unchecked")
      @Override
      public List<CustomTask> execute(CommandContext commandContext) {
        return (List<CustomTask>) commandContext.getDbSqlSession().selectList("selectCustomTaskList");
      }
    });
----

对于需要更复杂语句的用例，XML映射语句很有帮助。因此Activiti内部就使用XML映射语句，它可以确保底层功能。

假设某个用例下，需要基于id、name、type、userId等字段，查询附件数据！要实现这个用例，可以创建一个扩展了__org.activiti.engine.impl.AbstractQuery__的查询类__AttachmentQuery__，像下面这样：

[source,java,linenums]
----
public class AttachmentQuery extends AbstractQuery<AttachmentQuery, Attachment> {

  protected String attachmentId;
  protected String attachmentName;
  protected String attachmentType;
  protected String userId;

  public AttachmentQuery(ManagementService managementService) {
    super(managementService);
  }

  public AttachmentQuery attachmentId(String attachmentId){
    this.attachmentId = attachmentId;
    return this;
  }

  public AttachmentQuery attachmentName(String attachmentName){
    this.attachmentName = attachmentName;
    return this;
  }

  public AttachmentQuery attachmentType(String attachmentType){
    this.attachmentType = attachmentType;
    return this;
  }

  public AttachmentQuery userId(String userId){
    this.userId = userId;
    return this;
  }

  @Override
  public long executeCount(CommandContext commandContext) {
    return (Long) commandContext.getDbSqlSession()
                   .selectOne("selectAttachmentCountByQueryCriteria", this);
  }

  @Override
  public List<Attachment> executeList(CommandContext commandContext, Page page) {
    return commandContext.getDbSqlSession()
            .selectList("selectAttachmentByQueryCriteria", this);
  }
----

请注意在扩展__AbstractQuery__时，扩展类需要为super构造器传递一个__ManagementService__的实例，并需要实现__executeCount__与__executeList__来调用映射语句。

包含映射语句的XML文件像是下面这样：

[source,xml,linenums]
----
<mapper namespace="org.activiti.standalone.cfg.AttachmentMapper">

  <select id="selectAttachmentCountByQueryCriteria" parameterType="org.activiti.standalone.cfg.AttachmentQuery" resultType="long">
    select count(distinct RES.ID_)
    <include refid="selectAttachmentByQueryCriteriaSql"/>
  </select>

  <select id="selectAttachmentByQueryCriteria" parameterType="org.activiti.standalone.cfg.AttachmentQuery" resultMap="org.activiti.engine.impl.persistence.entity.AttachmentEntity.attachmentResultMap">
    ${limitBefore}
    select distinct RES.* ${limitBetween}
    <include refid="selectAttachmentByQueryCriteriaSql"/>
    ${orderBy}
    ${limitAfter}
  </select>

  <sql id="selectAttachmentByQueryCriteriaSql">
  from ${prefix}ACT_HI_ATTACHMENT RES
  <where>
   <if test="attachmentId != null">
     RES.ID_ = #{attachmentId}
   </if>
   <if test="attachmentName != null">
     and RES.NAME_ = #{attachmentName}
   </if>
   <if test="attachmentType != null">
     and RES.TYPE_ = #{attachmentType}
   </if>
   <if test="userId != null">
     and RES.USER_ID_ = #{userId}
   </if>
  </where>
  </sql>
</mapper>
----

可以在语句中使用例如分页、排序、表名前缀等功能（因为parameterType为__AbstractQuery__的子类）。请注意可以使用已定义的__org.activiti.engine.impl.persistence.entity.AttachmentEntity.attachmentResultMap__来映射结果。

最后，__AttachmentQuery__可以如下使用：

[source,java,linenums]
----
....
// 获取附件的总数 Get the total number of attachments
long count = new AttachmentQuery(managementService).count();

// 获取id为10025的附件 Get attachment with id 10025
Attachment attachment = new AttachmentQuery(managementService).attachmentId("10025").singleResult();

// 获取前10个附件 Get first 10 attachments
List<Attachment> attachments = new AttachmentQuery(managementService).listPage(0, 10);

// 获取用户kermit上传的所有附件 Get all attachments uploaded by user kermit
attachments = new AttachmentQuery(managementService).userId("kermit").list();
....
----


对于使用基于XML的映射语句的实际例子，请查看单元测试__org.activiti.standalone.cfg.CustomMybatisXMLMapperTest__与src/test/java/org/activiti/standalone/cfg/、src/test/resources/org/activiti/standalone/cfg/目录中的其它类与资源。

[[advanced.process.engine.configurators]]


=== 使用ProcessEngineConfigurator进行高级流程引擎配置  Advanced Process Engine configuration with a ProcessEngineConfigurator

深入流程引擎配置的高级方法是使用__ProcessEngineConfigurator__。方法是创建一个__org.activiti.engine.cfg.ProcessEngineConfigurator__接口的实现，并注入到流程引擎配置中：

[source,xml,linenums]
----
<bean id="processEngineConfiguration" class="...SomeProcessEngineConfigurationClass">

    ...

    <property name="configurators">
        <list>
            <bean class="com.mycompany.MyConfigurator">
                ...
            </bean>
        </list>
    </property>

    ...

</bean>
----

这个接口需要实现两个方法。__configure__方法，使用一个__ProcessEngineConfiguration__实例作为参数。可以使用这个方式添加自定义配置，并且这个方法会保证**在流程引擎创建之前，所有默认配置已经完成之后**调用。另一个方法是__getPriority__方法，可以指定配置器的顺序，以备某些配置器对其他的有依赖。

这种配置器的一个例子是<<chapter_ldap,LDAP集成>>，其中配置器用于将默认的用户与组管理类，替换为可以处理LDAP用户存储的实现。因此基本上配置器可以相当大地改变或调整流程引擎，也意味着非常高级的使用场景。另一个例子是使用自定义的版本替换流程引擎缓存：

[source,java,linenums]
----
public class ProcessDefinitionCacheConfigurator extends AbstractProcessEngineConfigurator {

    public void configure(ProcessEngineConfigurationImpl processEngineConfiguration) {
            MyCache myCache = new MyCache();
            processEngineConfiguration.setProcessDefinitionCache(enterpriseProcessDefinitionCache);
    }

}
----

也可以使用link:$$http://docs.oracle.com/javase/7/docs/api/java/util/ServiceLoader.html$$[ServiceLoader]方法，从classpath中自动发现流程引擎配置器。这意味着包含配置器实现的jar必须放在classpath下，并在jar的__META-INF/services__目录下包含名为**org.activiti.engine.cfg.ProcessEngineConfigurator**的文件。文件的内容必须是自定义实现的全限定类名。当流程引擎启动时，日志会显示找到这些配置器：

----
INFO  org.activiti.engine.impl.cfg.ProcessEngineConfigurationImpl  - Found 1 auto-discoverable Process Engine Configurators
INFO  org.activiti.engine.impl.cfg.ProcessEngineConfigurationImpl  - Found 1 Process Engine Configurators in total:
INFO  org.activiti.engine.impl.cfg.ProcessEngineConfigurationImpl  - class org.activiti.MyCustomConfigurator
----

请注意ServiceLoader方法可能在某些环境不能运行。可以通过ProcessEngineConfiguration的__enableConfiguratorServiceLoader__参数明确禁用（默认为true）。


[[advanced.task.query.switching]]


=== 高级查询API：在运行时与历史任务查询间无缝切换 Advanced query API: seamless switching between runtime and historic task querying

任何BPM用户界面的核心组件都是任务列表。一般来说，最终用户操作运行时的任务，在收件箱中通过不同设置进行过滤。有时也需要在这些列表中显示历史任务，并进行类似的过滤。为了简化代码，__TaskQuery__与__HistoricTaskInstanceQuery__有共同的父接口，其中包含了所有公共操作（大多数操作都是公共的）。

这个公共接口是__org.activiti.engine.task.TaskInfoQuery__类。__org.activiti.engine.task.Task__与__org.activiti.engine.task.HistoricTaskInstance__都有公共父类__org.activiti.engine.task.TaskInfo__（并带有公共参数），并将作为例如__list()__方法的返回值。然而，有时Java泛型会帮倒忙：如果想要直接使用__TaskInfoQuery__类型，将会像是这样：

[source,java,linenums]
----
TaskInfoQuery<? extends TaskInfoQuery<?,?>, ? extends TaskInfo> taskInfoQuery
----

呃……好吧。为了“解决”这个问题，可以使用__org.activiti.engine.task.TaskInfoQueryWrapper__类来避免泛型（下面的代码来自REST的代码，将返回一个任务列表，且用户可以选择查看进行中还是已完成的任务）：

[source,java,linenums]
----
TaskInfoQueryWrapper taskInfoQueryWrapper = null;
if (runtimeQuery) {
	taskInfoQueryWrapper = new TaskInfoQueryWrapper(taskService.createTaskQuery());
} else {
	taskInfoQueryWrapper = new TaskInfoQueryWrapper(historyService.createHistoricTaskInstanceQuery());
}

List<? extends TaskInfo> taskInfos = taskInfoQueryWrapper.getTaskInfoQuery().or()
	.taskNameLike("%k1%")
	.taskDueAfter(new Date(now.getTime() + (3 * 24L * 60L * 60L * 1000L)))
.endOr()
.list();
----


[[advanced.custom.session.manager]]


=== 通过覆盖标准SessionFactory自定义身份管理 Custom identity management by overriding standard SessionFactory

如果不想像<<chapter_ldap,LDAP集成>>中那样，使用完整的__ProcessEngineConfigurator__实现，但仍然希望将自定义的身份管理插入框架中，那么也可以直接覆盖__ProcessEngineConfiguration__中的__SessionFactory__类。在Spring中，可以简单地通过向__ProcessEngineConfiguration__ bean定义添加下面的代码实现：

[source,xml,linenums]
----
<bean id="processEngineConfiguration" class="...SomeProcessEngineConfigurationClass">

    ...

    <property name="customSessionFactories">
        <list>
            <bean class="com.mycompany.MyGroupManagerFactory"/>
            <bean class="com.mycompany.MyUserManagerFactory"/>
        </list>
    </property>

    ...

</bean>

----

__MyGroupManagerFactory__与__MyUserManagerFactory__需要实现__org.activiti.engine.impl.interceptor.SessionFactory__接口。对__openSession()__的调用，需要返回实际管理身份的自定义类的实现。对于组，需要是继承__org.activiti.engine.impl.persistence.entity.GroupEntityManager__的类，对于用户管理，需要是继承__org.activiti.engine.impl.persistence.entity.UserEntityManager__的类。下面的代码样例包含了一个自定义的组管理器工厂：

[source,java,linenums]
----
package com.mycompany;

import org.activiti.engine.impl.interceptor.Session;
import org.activiti.engine.impl.interceptor.SessionFactory;
import org.activiti.engine.impl.persistence.entity.GroupIdentityManager;

public class MyGroupManagerFactory implements SessionFactory {

	@Override
	public Class<?> getSessionType() {
		return GroupIdentityManager.class;
	}

	@Override
	public Session openSession() {
		return new MyCompanyGroupManager();
	}

}
----

实际工作由这个工厂创建的__MyCompanyGroupManager__进行。但不需要覆盖__GroupEntityManager__的所有成员，只需要覆盖使用场景需要的那些即可。下面的样例展示了可能的样子（只展示一部分成员）：

[source,java,linenums]
----
public class MyCompanyGroupManager extends GroupEntityManager {

    private static Logger log = LoggerFactory.getLogger(MyCompanyGroupManager.class);

    @Override
    public List<Group> findGroupsByUser(String userId) {
        log.debug("findGroupByUser called with userId: " + userId);
        return super.findGroupsByUser(userId);
    }

    @Override
    public List<Group> findGroupByQueryCriteria(GroupQueryImpl query, Page page) {
        log.debug("findGroupByQueryCriteria called, query: " + query + " page: " + page);
        return super.findGroupByQueryCriteria(query, page);
    }

    @Override
    public long findGroupCountByQueryCriteria(GroupQueryImpl query) {
        log.debug("findGroupCountByQueryCriteria called, query: " + query);
        return super.findGroupCountByQueryCriteria(query);
    }

    @Override
    public Group createNewGroup(String groupId) {
        throw new UnsupportedOperationException();
    }

    @Override
    public void deleteGroup(String groupId) {
        throw new UnsupportedOperationException();
    }
}
----

在适当的方法中添加你自己的实现，以插入自己的身份管理解决方案。需要自行判断要覆盖基类中的那些成员。例如下面的调用：

[source,java,linenums]
----
long potentialOwners = identityService.createUserQuery().memberOfGroup("management").count();
----

会调用__UserIdentityManager__接口的下列成员：

[source,java,linenums]
----
List<User> findUserByQueryCriteria(UserQueryImpl query, Page page);
----

<<chapter_ldap,LDAP集成>>中的代码包含了如何实现这些的完整示例。可以在GitHub查看代码，特别是link:$$https://github.com/Activiti/Activiti/blob/master/modules/activiti-ldap/src/main/java/org/activiti/ldap/LDAPGroupManager.java$$[LDAPGroupManager]与link:$$https://github.com/Activiti/Activiti/blob/master/modules/activiti-ldap/src/main/java/org/activiti/ldap/LDAPUserManager.java$$[LDAPUserManager]。


[[advanced.safe.bpmn.xml]]


=== 启用安全BPMN 2.0 XML (Enable safe BPMN 2.0 xml)

在大多数情况下，部署至Activiti引擎的BPMN 2.0流程都在例如开发团队的严格控制下。然而，有的时候能够向引擎上传任意的BPMN 2.0 XML很诱人。在这种情况下，需要考虑动机不良的用户可能会像link:$$http://www.jorambarrez.be/blog/2013/02/19/uploading-a-funny-xml-can-bring-down-your-server/$$[这里]描述的一样，搞坏服务器。

要避免上面链接中描述的攻击，可以在流程引擎配置中设置__enableSafeBpmnXml__参数：

[source,xml,linenums]
----
<property name="enableSafeBpmnXml" value="true"/>
----

**默认情况下这个功能是禁用的！**原因是它依赖link:$$http://download.java.net/jdk7/archive/b123/docs/api/javax/xml/transform/stax/StAXSource.html$$[StaxSource]类。而不幸的是，某些平台（例如JDK6， JBoss，等等）不能使用这个类（由于过时的XML解析器实现），因此不能启用安全BPMN 2.0 XML功能。

如果Activiti运行的平台支持，请一定要启用这个功能。


[[advanced.event.logging]]


=== 事件记录（试验性） Event logging (Experimental)

从Activiti 5.16开始，引入了（试验性）的事件记录机制。记录机制基于<<eventDispatcher,Activiti引擎的事件机制>>的一般用途，并默认禁用。其思想是，来源于引擎的事件会被捕获，并创建一个包含了所有事件数据（甚至更多）的映射，提供给__org.activiti.engine.impl.event.logger.EventFlusher__，由它将这些数据刷入其他地方。默认情况下，使用简单的基于数据库的事件处理/刷入，会使用Jackson将上述映射序列化为JSON，并将其作为__EventLogEntryEntity__接口存入数据库。如果不使用事件记录，可以删除这个表。

要启用数据库记录：

[source,java,linenums]
----
processEngineConfiguration.setEnableDatabaseEventLogging(true);
----

或在运行时：

[source,xml,linenums]
----
databaseEventLogger = new EventLogger(processEngineConfiguration.getClock());
runtimeService.addEventListener(databaseEventLogger);
----

可以扩展EventLogger类。如果默认的数据库记录不符合要求，需要覆盖__createEventFlusher()__方法返回一个__org.activiti.engine.impl.event.logger.EventFlusher__接口的实例。可以通过Activiti的__managementService.getEventLogEntries(startLogNr, size);__获取__EventLogEntryEntity__实例。

容易看出这个表中的数据可以通过JSON放入大数据NoSQL存储，例如MongoDB，Elastic Search，等等。也容易看出这里使用的类（org.activiti.engine.impl.event.logger.EventLogger/EventFlusher与许多其他EventHandler类）是可插入的，可以按你的使用场景调整（例如不将JSON存入数据库，而是将其直接发送给一个队列或大数据存储）。

请注意这个事件记录机制是额外于Activiti的“传统”历史管理器的。尽管所有数据都在数据库表中，但并未对查询或快速恢复做优化。实际使用场景是末端审计并将其存入大数据存储。

=== 禁用批量插入 Disabling bulk inserts

默认情况下，引擎会将对同一个数据库表的多个插入语句组合在一起，作为__批量插入__，这样能够提高性能，并已在所有支持的数据库中测试与实现了。

然而，支持与测试过的数据库，可能有某个特定版本不支持批量插入（例如有报告说DB2在z/OS上不支持，尽管一般来说DB2是支持的），可以在流程引擎配置中禁用批量插入：

[source,xml,linenums]
----
<property name="bulkInsertEnabled" value="false" />
----

[[advancedSecureScripting]]
=== 安全脚本 Secure Scripting

**试验性**：安全脚本功能随Activiti 5.21发布。

默认情况下，使用<<bpmnScriptTask,脚本任务>>时，执行的脚本与Java代理具有相似的能力。可以完全访问JVM，永远运行（无限循环），或占用大量内存。然而，Java代理需要撰写并放在classpath的jar中，与流程定义的生命周期不同。最终用户一般不会撰写Java代理，因为这基本上是开发者的工作。

然而脚本是流程定义的一部分，具有相同的生命周期。脚本任务不需要额外的jar部署步骤，而是在流程部署后就可以执行。有时，脚本任务中的脚本不是由开发者撰写的。这就有一个上面提到的问题：脚本可以完全访问JVM，也可以在执行脚本时阻塞许多系统资源。因此允许来自几乎任何人的脚本不是一个好主意。

要解决这个问题，可以启用__安全脚本__功能。目前，这个功能只实现了__javascript__脚本。要启用它，向你的项目添加__activiti-secure-javascript__依赖。使用Maven时：

[source,xml,linenums]
----
<dependency>
    <groupId>org.activiti</groupId>
    <artifactId>activiti-secure-javascript</artifactId>
    <version>${activiti.version}</version>
</dependency>
----

添加这个依赖会同时引入Rhino依赖（参见link:$https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino$$[https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino]）。Rhino是一个用于JDK的javascript引擎。过去包含在JDK版本6与7中，并已被Nashorn引擎取代。然而，Rhino项目仍然在继续开发。许多功能（包括Activiti用于实现安全脚本的）都在之后才加入。在撰写本手册的时候，Nashorn**还没有**实现安全脚本功能需要的功能。

这意味着脚本之间可能要做一些（基本很少）改变（例如，Rhino使用__importPackage__，而Nashorn使用__load()__）。这些改变与将脚本从JDK 7切换至8相似。

通过专门的__Configurator__对象配置安全脚本，并在流程引擎实例化之前将其传递给流程引擎配置：

[source,java,linenums]
----
SecureJavascriptConfigurator configurator = new SecureJavascriptConfigurator()
  .setWhiteListedClasses(new HashSet<String>(Arrays.asList("java.util.ArrayList")))
  .setMaxStackDepth(10)
  .setMaxScriptExecutionTime(3000L)
  .setMaxMemoryUsed(3145728L)
  .setNrOfInstructionsBeforeStateCheckCallback(10);

processEngineConfig.addConfigurator(configurator);
----

可以使用下列设置：

* *enableClassWhiteListing*: 为true时，会黑名单所有类。希望运行的所有类都需要添加入白名单，这样就严格控制了暴露给脚本的东西。默认为__false__。
* *whiteListedClasses*: 一个全限定类名字符串的集合，表示允许脚本中使用的类。例如，要在脚本中暴露__execution__对象，需要在这个集合中添加__org.activiti.engine.impl.persistence.entity.ExecutionEntity__字符串。默认为__空__。
* *maxStackDepth*: 限制在脚本中调用函数时的最大栈深度。可以用于避免由于递归调用脚本中定义的方法，而导致的栈溢出异常。默认为__-1__（禁用）。
* *maxScriptExecutionTime*: 脚本允许运行的最大时间。默认为__-1__（禁用）。
* *maxMemoryUsed*: 脚本允许使用的最大内存数量，以字节计。请注意脚本引擎自己也要需要一定量的内存，也会算在这里。默认为__-1__（禁用）。
* *nrOfInstructionsBeforeStateCheckCallback*: 脚本每执行x个指令，就通过回调函数进行一次最大脚本执行时间与内存检测。请注意这不是指脚本指令，而是指java字节码指令（这意味着一行脚本可能有上百行字节码指令）。默认为100。

__请注意：____maxMemoryUsed__设置只能用于支持com.sun.management.ThreadMXBean#getThreadAllocatedBytes()方法的JVM。Oracle JDK支持它。

也有ScriptExecutionListener与ScriptTaskListener的安全形式：__org.activiti.scripting.secure.listener.SecureJavascriptExecutionListener__与__org.activiti.scripting.secure.listener.SecureJavascriptTaskListener__。

像这样使用：

[source,xml,linenums]
----
<activiti:executionListener event="start" class="org.activiti.scripting.secure.listener.SecureJavascriptExecutionListener">
  <activiti:field name="script">
	  <activiti:string>
		  <![CDATA[
        execution.setVariable('test');
			]]>
	  </activiti:string>
	</activiti:field>
  <activiti:field name="language" stringValue="javascript" />
</activiti:executionListener>
----

演示不安全脚本以及如何通过__安全脚本__功能将其变得安全的例子，可以查看link:$$https://github.com/Activiti/Activiti/tree/master/modules/activiti-secure-javascript/src/test/resources$$[GitHub上的单元测试]
